"""Safe, create-missing-only GitHub Actions integration for consumers."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Callable

from agentgov import __version__


CI_INTEGRATION_CONTRACT_VERSION = "1.0"
WORKFLOW_PATH = Path(".github/workflows/agentgov.yml")
STABLE_CONSUMER_VERSION = "0.1.0"
STABLE_CONSUMER_WHEEL_SHA256 = (
    "1e22d736a8701377f8ab7f15bf4ea5a34c80ae0ae944ce84973da6925ffbb18f"
)
_VERSION_RE = re.compile(
    r"^[0-9]+\.[0-9]+\.[0-9]+(?:(?:a|b|rc)[0-9]+|\.dev[0-9]+)?$"
)
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_MANAGED_HEADER_RE = re.compile(
    r"\A# Generated by AgentGov integration; pinned release "
    r"(?P<version>[0-9]+\.[0-9]+\.[0-9]+"
    r"(?:(?:a|b|rc)[0-9]+|\.dev[0-9]+)?)\.\n"
)
_MANAGED_SHA_RE = re.compile(
    r'^          AGENTGOV_WHEEL_SHA256: "(?P<sha256>[0-9a-f]{64})"$',
    re.MULTILINE,
)


class IntegrationAction(str, Enum):
    CREATE = "CREATE"
    PRESERVE = "PRESERVE"
    CONFLICT = "CONFLICT"


class ConsumerCIState(str, Enum):
    MANAGED = "managed"
    CUSTOM = "custom"
    MISSING = "missing"
    CONFLICT = "conflict"


@dataclass(frozen=True)
class IntegrationItem:
    action: IntegrationAction
    path: Path
    reason: str
    content: str | None = None


@dataclass(frozen=True)
class IntegrationPlan:
    root: Path
    item: IntegrationItem

    @property
    def has_conflict(self) -> bool:
        return self.item.action is IntegrationAction.CONFLICT


@dataclass(frozen=True)
class IntegrationResult:
    root: Path
    created_files: tuple[Path, ...]


@dataclass(frozen=True)
class ConsumerCIStatus:
    state: ConsumerCIState
    workflow_paths: tuple[Path, ...]
    managed_path: Path
    message: str


@dataclass(frozen=True)
class ManagedConsumerRelease:
    version: str
    wheel_sha256: str


class IntegrationConflictError(Exception):
    """Raised when a reviewed CI integration plan is no longer safe."""


def render_consumer_workflow(
    *,
    version: str = STABLE_CONSUMER_VERSION,
    wheel_url: str | None = None,
    wheel_sha256: str = STABLE_CONSUMER_WHEEL_SHA256,
) -> str:
    """Render the portable consumer workflow pinned to one verified release."""

    if not _VERSION_RE.fullmatch(version):
        raise ValueError(f"unsupported consumer AgentGov version: {version}")
    wheel = f"agent_governance_starter-{version}-py3-none-any.whl"
    expected_url = (
        "https://github.com/Andy-JunXiong/agent-governance-starter/"
        f"releases/download/v{version}/{wheel}"
    )
    resolved_url = wheel_url or expected_url
    if resolved_url != expected_url:
        raise ValueError("consumer wheel URL must be the matching fixed-tag release asset")
    if not _SHA256_RE.fullmatch(wheel_sha256):
        raise ValueError("consumer wheel SHA-256 must be 64 lowercase hexadecimal characters")
    version_core = re.match(r"^([0-9]+)\.([0-9]+)\.([0-9]+)", version)
    if version_core is None:
        raise ValueError(f"unsupported consumer AgentGov version: {version}")
    supports_status_markdown = tuple(
        int(part) for part in version_core.groups()
    ) >= (0, 2, 0)
    status_summary = ""
    status_artifact = ""
    schedule_trigger = ""
    update_manifest_step = ""
    update_command = (
        "agentgov update --check . --non-interactive --format json > "
        "agentgov-update.json"
    )
    upgrade_review_step = ""
    if supports_status_markdown:
        schedule_trigger = """  schedule:
    - cron: "0 13 * * 1-5"
"""
        update_manifest_step = """
      - name: Download latest stable AgentGov manifest
        continue-on-error: true
        shell: bash
        run: |
          curl --fail --location --silent --show-error \\
            "https://github.com/Andy-JunXiong/agent-governance-starter/releases/latest/download/release-manifest.json" \\
            --output agentgov-latest-manifest.json
"""
        update_command = (
            "agentgov update --check . --manifest agentgov-latest-manifest.json "
            "--non-interactive --format json > agentgov-update.json"
        )
        upgrade_review_step = """
      - name: Build consumer-local AgentGov upgrade review
        continue-on-error: true
        run: |
          agentgov review upgrade . \\
            --manifest agentgov-latest-manifest.json \\
            --output agentgov-upgrade-review
"""
        status_summary = """          agentgov status . --format markdown --non-interactive > agentgov-status.md || true
          cat agentgov-status.md >> "$GITHUB_STEP_SUMMARY"
          if [ -f agentgov-upgrade-review/UPGRADE_REVIEW.md ]; then
            echo "" >> "$GITHUB_STEP_SUMMARY"
            cat agentgov-upgrade-review/UPGRADE_REVIEW.md >> "$GITHUB_STEP_SUMMARY"
          fi
"""
        status_artifact = (
            "            agentgov-status.md\n"
            "            agentgov-upgrade-review\n"
        )
    return f"""# Generated by AgentGov integration; pinned release {version}.
name: AgentGov

on:
  pull_request:
  push:
  workflow_dispatch:
{schedule_trigger}
permissions:
  contents: read

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.11"

      - name: Download and verify pinned AgentGov
        shell: bash
        env:
          AGENTGOV_WHEEL_URL: "{resolved_url}"
          AGENTGOV_WHEEL_SHA256: "{wheel_sha256}"
        run: |
          curl --fail --location --silent --show-error "$AGENTGOV_WHEEL_URL" --output "$RUNNER_TEMP/agentgov.whl"
          echo "$AGENTGOV_WHEEL_SHA256  $RUNNER_TEMP/agentgov.whl" | sha256sum --check -
          python -m pip install --no-deps "$RUNNER_TEMP/agentgov.whl"
{update_manifest_step}
      - name: Record update state
        continue-on-error: true
        run: {update_command}
{upgrade_review_step}
      - name: Check repository and write JSON report
        run: agentgov report repository . --format json --output agentgov-report.json

      - name: Add visible governance summary
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          agentgov report repository . --format markdown --output agentgov-report.md || true
          cat agentgov-report.md >> "$GITHUB_STEP_SUMMARY"
{status_summary}
      - name: Upload AgentGov reports
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: agentgov-reports
          path: |
            agentgov-report.json
            agentgov-report.md
{status_artifact}            agentgov-update.json
          if-no-files-found: warn

      - name: Preserve human authority boundary
        if: always()
        run: echo "AgentGov findings do not authorize merge, release, deploy, or production execution."
"""


def inspect_managed_workflow_content(content: str) -> ManagedConsumerRelease | None:
    """Recognize any byte-exact AgentGov-managed pinned release workflow."""

    header = _MANAGED_HEADER_RE.match(content)
    sha_match = _MANAGED_SHA_RE.search(content)
    if header is None or sha_match is None:
        return None
    version = header.group("version")
    wheel_sha256 = sha_match.group("sha256")
    try:
        expected = render_consumer_workflow(
            version=version,
            wheel_sha256=wheel_sha256,
        )
    except ValueError:
        return None
    if content != expected:
        return None
    return ManagedConsumerRelease(version=version, wheel_sha256=wheel_sha256)


def _resolve_root(root: Path) -> Path:
    if root.is_symlink():
        raise ValueError(f"repository root must not be a symbolic link: {root}")
    if not root.exists():
        raise FileNotFoundError(root)
    if not root.is_dir():
        raise ValueError(f"repository root is not a directory: {root}")
    return root.resolve()


def plan_github_actions_integration(root: Path) -> IntegrationPlan:
    """Plan one create-missing-only workflow without writing."""

    resolved = _resolve_root(root)
    target = resolved / WORKFLOW_PATH
    expected = render_consumer_workflow()
    if target.is_symlink() or target.is_dir():
        item = IntegrationItem(
            IntegrationAction.CONFLICT,
            WORKFLOW_PATH,
            "target must be a regular file and requires human resolution",
        )
    elif target.is_file():
        try:
            current = target.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ValueError(f"cannot read existing workflow: {exc}") from exc
        managed_release = inspect_managed_workflow_content(current)
        if managed_release is not None:
            item = IntegrationItem(
                IntegrationAction.PRESERVE,
                WORKFLOW_PATH,
                f"managed AgentGov {managed_release.version} workflow is already configured",
            )
        else:
            item = IntegrationItem(
                IntegrationAction.CONFLICT,
                WORKFLOW_PATH,
                "existing workflow differs and will not be overwritten",
            )
    else:
        current = resolved
        conflict: Path | None = None
        for part in WORKFLOW_PATH.parts[:-1]:
            current = current / part
            if current.is_symlink() or (current.exists() and not current.is_dir()):
                conflict = current.relative_to(resolved)
                break
        if conflict is not None:
            item = IntegrationItem(
                IntegrationAction.CONFLICT,
                WORKFLOW_PATH,
                f"parent path {conflict.as_posix()} is not a safe directory",
            )
        else:
            item = IntegrationItem(
                IntegrationAction.CREATE,
                WORKFLOW_PATH,
                f"add pinned AgentGov {STABLE_CONSUMER_VERSION} pull-request governance checks",
                expected,
            )
    return IntegrationPlan(resolved, item)


def render_integration_plan_json(
    plan: IntegrationPlan,
    *,
    non_interactive: bool,
) -> str:
    payload = {
        "contract_version": CI_INTEGRATION_CONTRACT_VERSION,
        "tool": {"name": "agentgov", "version": __version__},
        "repository": str(plan.root),
        "mode": "dry_run",
        "interaction": "non_interactive" if non_interactive else "no_prompt",
        "integration": "github-actions",
        "item": {
            "action": plan.item.action.value,
            "path": plan.item.path.as_posix(),
            "reason": plan.item.reason,
            "content": plan.item.content,
        },
        "authority_boundary": {
            "repository_modified": False,
            "write_authorized": False,
            "installs_project_dependencies": False,
            "runs_project_or_production_workflows": False,
            "authorizes_git_or_release_operations": False,
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def request_integration_confirmation(
    plan: IntegrationPlan,
    *,
    decision_reader: Callable[[str], str],
    is_interactive_terminal: bool,
) -> bool:
    if not is_interactive_terminal:
        return False
    decision = decision_reader(
        f'Type INTEGRATE to create "{plan.item.path.as_posix()}" in '
        f'"{plan.root}": '
    )
    return decision == "INTEGRATE"


def apply_integration_plan(plan: IntegrationPlan) -> IntegrationResult:
    """Apply an unchanged CREATE plan using exclusive file creation."""

    if plan.has_conflict:
        raise IntegrationConflictError("integration plan contains a conflict")
    if plan.item.action is IntegrationAction.PRESERVE:
        return IntegrationResult(plan.root, ())
    if plan.item.content is None:
        raise IntegrationConflictError("planned workflow has no deterministic content")

    target = plan.root / plan.item.path
    current = plan.root
    for part in plan.item.path.parts[:-1]:
        current = current / part
        if current.is_symlink():
            raise IntegrationConflictError(
                f"parent path became a symbolic link: "
                f"{current.relative_to(plan.root).as_posix()}"
            )
        if current.exists() and not current.is_dir():
            raise IntegrationConflictError(
                f"parent path became a non-directory: "
                f"{current.relative_to(plan.root).as_posix()}"
            )
    if target.exists() or target.is_symlink():
        raise IntegrationConflictError(
            f"planned target appeared and was not overwritten: {plan.item.path.as_posix()}"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        with target.open("x", encoding="utf-8", newline="") as handle:
            handle.write(plan.item.content)
    except FileExistsError as exc:
        raise IntegrationConflictError(
            f"planned target appeared and was not overwritten: {plan.item.path.as_posix()}"
        ) from exc
    return IntegrationResult(plan.root, (plan.item.path,))


def inspect_consumer_ci(root: Path) -> ConsumerCIStatus:
    """Inspect whether an adopting repository runs AgentGov in GitHub Actions."""

    resolved = _resolve_root(root)
    managed = resolved / WORKFLOW_PATH
    if managed.is_symlink() or managed.is_dir():
        return ConsumerCIStatus(
            ConsumerCIState.CONFLICT,
            (WORKFLOW_PATH,),
            WORKFLOW_PATH,
            "managed workflow path is not a safe regular file",
        )
    if managed.is_file():
        text = managed.read_text(encoding="utf-8")
        managed_release = inspect_managed_workflow_content(text)
        if managed_release is not None:
            return ConsumerCIStatus(
                ConsumerCIState.MANAGED,
                (WORKFLOW_PATH,),
                WORKFLOW_PATH,
                f"managed pinned AgentGov {managed_release.version} workflow is active",
            )

    workflow_root = resolved / ".github/workflows"
    matches: list[Path] = []
    if workflow_root.is_dir() and not workflow_root.is_symlink():
        for path in sorted((*workflow_root.glob("*.yml"), *workflow_root.glob("*.yaml"))):
            if not path.is_file() or path.is_symlink():
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeError):
                continue
            if (
                "agentgov check repository" in text
                or "agentgov report repository" in text
            ):
                matches.append(path.relative_to(resolved))
    if matches:
        return ConsumerCIStatus(
            ConsumerCIState.CUSTOM,
            tuple(matches),
            WORKFLOW_PATH,
            "a custom GitHub Actions workflow invokes AgentGov",
        )
    if managed.is_file():
        return ConsumerCIStatus(
            ConsumerCIState.CONFLICT,
            (WORKFLOW_PATH,),
            WORKFLOW_PATH,
            "agentgov.yml exists but does not invoke the expected repository check",
        )
    return ConsumerCIStatus(
        ConsumerCIState.MISSING,
        (),
        WORKFLOW_PATH,
        "AgentGov is manual-only because no GitHub Actions invocation was found",
    )
