"""Safe, create-missing-only GitHub Actions integration for consumers."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Callable

from agentgov import __version__


CI_INTEGRATION_CONTRACT_VERSION = "1.0"
WORKFLOW_PATH = Path(".github/workflows/agentgov.yml")
UPGRADE_WORKFLOW_PATH = Path(".github/workflows/agentgov-upgrade.yml")
STABLE_CONSUMER_VERSION = "0.1.0"
STABLE_CONSUMER_WHEEL_SHA256 = (
    "1e22d736a8701377f8ab7f15bf4ea5a34c80ae0ae944ce84973da6925ffbb18f"
)
_VERSION_RE = re.compile(
    r"^[0-9]+\.[0-9]+\.[0-9]+(?:(?:a|b|rc)[0-9]+|\.dev[0-9]+)?$"
)
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_MANAGED_HEADER_RE = re.compile(
    r"\A# Generated by AgentGov integration; pinned release "
    r"(?P<version>[0-9]+\.[0-9]+\.[0-9]+"
    r"(?:(?:a|b|rc)[0-9]+|\.dev[0-9]+)?)\.\n"
)
_MANAGED_UPGRADE_HEADER_RE = re.compile(
    r"\A# Generated by AgentGov upgrade integration; pinned release "
    r"(?P<version>[0-9]+\.[0-9]+\.[0-9]+"
    r"(?:(?:a|b|rc)[0-9]+|\.dev[0-9]+)?)\.\n"
)
_MANAGED_SHA_RE = re.compile(
    r'^          AGENTGOV_WHEEL_SHA256: "(?P<sha256>[0-9a-f]{64})"$',
    re.MULTILINE,
)


class IntegrationAction(str, Enum):
    CREATE = "CREATE"
    PRESERVE = "PRESERVE"
    CONFLICT = "CONFLICT"


class ConsumerCIState(str, Enum):
    MANAGED = "managed"
    CUSTOM = "custom"
    MISSING = "missing"
    CONFLICT = "conflict"


@dataclass(frozen=True)
class IntegrationItem:
    action: IntegrationAction
    path: Path
    reason: str
    content: str | None = None


@dataclass(frozen=True)
class IntegrationPlan:
    root: Path
    item: IntegrationItem

    @property
    def has_conflict(self) -> bool:
        return self.item.action is IntegrationAction.CONFLICT


@dataclass(frozen=True)
class IntegrationResult:
    root: Path
    created_files: tuple[Path, ...]


@dataclass(frozen=True)
class ConsumerCIStatus:
    state: ConsumerCIState
    workflow_paths: tuple[Path, ...]
    managed_path: Path
    message: str


@dataclass(frozen=True)
class ManagedConsumerRelease:
    version: str
    wheel_sha256: str


class IntegrationConflictError(Exception):
    """Raised when a reviewed CI integration plan is no longer safe."""


def render_consumer_workflow(
    *,
    version: str = STABLE_CONSUMER_VERSION,
    wheel_url: str | None = None,
    wheel_sha256: str = STABLE_CONSUMER_WHEEL_SHA256,
    _surface: str = "governance",
) -> str:
    """Render the portable consumer workflow pinned to one verified release."""

    if not _VERSION_RE.fullmatch(version):
        raise ValueError(f"unsupported consumer AgentGov version: {version}")
    wheel = f"agent_governance_starter-{version}-py3-none-any.whl"
    expected_url = (
        "https://github.com/Andy-JunXiong/agent-governance-starter/"
        f"releases/download/v{version}/{wheel}"
    )
    resolved_url = wheel_url or expected_url
    if resolved_url != expected_url:
        raise ValueError("consumer wheel URL must be the matching fixed-tag release asset")
    if not _SHA256_RE.fullmatch(wheel_sha256):
        raise ValueError("consumer wheel SHA-256 must be 64 lowercase hexadecimal characters")
    version_core = re.match(r"^([0-9]+)\.([0-9]+)\.([0-9]+)", version)
    if version_core is None:
        raise ValueError(f"unsupported consumer AgentGov version: {version}")
    version_tuple = tuple(int(part) for part in version_core.groups())
    supports_status_markdown = version_tuple >= (0, 2, 0)
    supports_upgrade_writer = version_tuple >= (0, 3, 0)
    wheel_install_script = """          curl --fail --location --silent --show-error "$AGENTGOV_WHEEL_URL" --output "$RUNNER_TEMP/agentgov.whl"
          echo "$AGENTGOV_WHEEL_SHA256  $RUNNER_TEMP/agentgov.whl" | sha256sum --check -
          python -m pip install --no-deps "$RUNNER_TEMP/agentgov.whl"
"""
    if version_tuple >= (0, 2, 1):
        wheel_install_script = f"""          wheel_path="$RUNNER_TEMP/{wheel}"
          curl --fail --location --silent --show-error "$AGENTGOV_WHEEL_URL" --output "$wheel_path"
          echo "$AGENTGOV_WHEEL_SHA256  $wheel_path" | sha256sum --check -
          python -m pip install --no-deps "$wheel_path"
"""
    status_summary = ""
    status_artifact = ""
    workflow_permissions = "permissions:\n  contents: read"
    schedule_trigger = ""
    workflow_dispatch_trigger = "  workflow_dispatch:\n"
    update_manifest_step = ""
    update_command = (
        "agentgov update --check . --non-interactive --format json > "
        "agentgov-update.json"
    )
    upgrade_review_step = ""
    proposal_job = ""
    benefit_baseline_step = ""
    benefit_monitor_step = ""
    benefit_summary = ""
    benefit_artifact = ""
    benefit_baseline_upload = ""
    development_monitor_step = ""
    development_monitor_artifact = ""
    governance_job_outputs = ""
    finding_annotations_step = ""
    governance_gate_step = ""
    notification_job = ""
    visible_summary = '          cat agentgov-report.md >> "$GITHUB_STEP_SUMMARY"\n'
    report_continue = ""
    if supports_status_markdown:
        schedule_trigger = """  schedule:
    - cron: "0 13 * * 1-5"
"""
        update_manifest_step = """
      - name: Download latest stable AgentGov manifest
        continue-on-error: true
        shell: bash
        run: |
          curl --fail --location --silent --show-error \\
            "https://github.com/Andy-JunXiong/agent-governance-starter/releases/latest/download/release-manifest.json" \\
            --output agentgov-latest-manifest.json
"""
        update_command = (
            "agentgov update --check . --manifest agentgov-latest-manifest.json "
            "--non-interactive --format json > agentgov-update.json"
        )
        upgrade_review_step = """
      - name: Build consumer-local AgentGov upgrade review
        continue-on-error: true
        run: |
          agentgov review upgrade . \\
            --manifest agentgov-latest-manifest.json \\
            --output agentgov-upgrade-review
"""
        status_summary = """          agentgov status . --format markdown --non-interactive > agentgov-status.md || true
          cat agentgov-status.md >> "$GITHUB_STEP_SUMMARY"
          if [ -f agentgov-upgrade-review/UPGRADE_REVIEW.md ]; then
            echo "" >> "$GITHUB_STEP_SUMMARY"
            cat agentgov-upgrade-review/UPGRADE_REVIEW.md >> "$GITHUB_STEP_SUMMARY"
          fi
"""
        status_artifact = (
            "            agentgov-status.md\n"
            "            agentgov-upgrade-review\n"
        )
    if supports_upgrade_writer:
        workflow_permissions = "permissions:\n  contents: read\n  actions: read"
        workflow_dispatch_trigger = """  workflow_dispatch:
    inputs:
      publish_development_monitor:
        description: "Build and upload the source-limited Development Monitor"
        required: false
        type: boolean
        default: false
      development_export:
        description: "Optional repository-relative metadata-only development export"
        required: false
        type: string
        default: ""
"""
        development_monitor_step = """
      - name: Build opt-in Development Monitor
        if: github.event_name == 'workflow_dispatch' && inputs.publish_development_monitor
        shell: bash
        env:
          AGENTGOV_DEVELOPMENT_EXPORT: ${{ inputs.development_export }}
        run: |
          monitor_args=(--scope ci_only)
          if [ -n "$AGENTGOV_DEVELOPMENT_EXPORT" ]; then
            monitor_args=(--scope exported_development --export "$AGENTGOV_DEVELOPMENT_EXPORT")
            if find .agentgov/events -maxdepth 1 -type f -name 'evt-*.json' -print -quit 2>/dev/null | grep -q .; then
              monitor_args=(--scope combined --export "$AGENTGOV_DEVELOPMENT_EXPORT")
            fi
          fi
          agentgov monitor development . \\
            "${monitor_args[@]}" \\
            --format html \\
            --output agentgov-development-monitor.html
"""
        development_monitor_artifact = """
      - name: Upload opt-in Development Monitor
        if: always() && github.event_name == 'workflow_dispatch' && inputs.publish_development_monitor
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: agentgov-development-monitor
          path: agentgov-development-monitor.html
          if-no-files-found: error
          retention-days: 30
"""
        benefit_baseline_step = """
      - name: Restore previous trusted AgentGov main baseline
        if: always()
        continue-on-error: true
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          AGENTGOV_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          runs_file="$RUNNER_TEMP/agentgov-runs.json"
          artifacts_file="$RUNNER_TEMP/agentgov-artifacts.json"
          baseline_zip="$RUNNER_TEMP/agentgov-baseline.zip"
          baseline_dir="$RUNNER_TEMP/agentgov-baseline"
          gh api "/repos/$GITHUB_REPOSITORY/actions/workflows/agentgov.yml/runs?branch=$AGENTGOV_DEFAULT_BRANCH&status=completed&per_page=20" > "$runs_file"
          prior_run_id="$(jq -r --arg current "$GITHUB_RUN_ID" '[.workflow_runs[] | select((.id | tostring) != $current) | select(.event == "push" or .event == "schedule" or .event == "workflow_dispatch") | select(.conclusion == "success" or .conclusion == "failure")] | first | .id // empty' "$runs_file")"
          if [ -z "$prior_run_id" ]; then
            echo "No prior trusted default-branch AgentGov run is available."
            exit 0
          fi
          gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$prior_run_id/artifacts" > "$artifacts_file"
          artifact_id="$(jq -r '[.artifacts[] | select(.name == "agentgov-main-baseline") | select(.expired == false)] | first | .id // empty' "$artifacts_file")"
          if [ -z "$artifact_id" ]; then
            echo "Prior run has no retained AgentGov main baseline."
            exit 0
          fi
          gh api "/repos/$GITHUB_REPOSITORY/actions/artifacts/$artifact_id/zip" > "$baseline_zip"
          mkdir -p "$baseline_dir"
          unzip -q "$baseline_zip" -d "$baseline_dir"
          test -f "$baseline_dir/agentgov-report.json"
          test -f "$baseline_dir/benefit-monitor.json"
"""
        benefit_monitor_step = """
      - name: Build continuous AgentGov benefit monitor
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          baseline_args=()
          if [ -f "$RUNNER_TEMP/agentgov-baseline/agentgov-report.json" ] && [ -f "$RUNNER_TEMP/agentgov-baseline/benefit-monitor.json" ]; then
            baseline_args+=(--baseline-report "$RUNNER_TEMP/agentgov-baseline/agentgov-report.json")
            baseline_args+=(--baseline-monitor "$RUNNER_TEMP/agentgov-baseline/benefit-monitor.json")
          fi
          observed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          agentgov benefits monitor agentgov-report.json \\
            "${baseline_args[@]}" \\
            --repository "$GITHUB_REPOSITORY" \\
            --ref "$GITHUB_REF" \\
            --commit "$GITHUB_SHA" \\
            --run-id "$GITHUB_RUN_ID" \\
            --run-attempt "$GITHUB_RUN_ATTEMPT" \\
            --event "$GITHUB_EVENT_NAME" \\
            --observed-at "$observed_at" \\
            --output agentgov-benefit-monitor
"""
        governance_job_outputs = """    outputs:
      monitor_state: ${{ steps.delivery_state.outputs.monitor_state }}
"""
        report_continue = "        continue-on-error: true\n"
        visible_summary = """          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            if [ -f agentgov-benefit-monitor/PR_REVIEW.md ]; then
              cat agentgov-benefit-monitor/PR_REVIEW.md >> "$GITHUB_STEP_SUMMARY"
            else
              cat agentgov-report.md >> "$GITHUB_STEP_SUMMARY"
            fi
          else
            cat agentgov-report.md >> "$GITHUB_STEP_SUMMARY"
            agentgov status . --format markdown --non-interactive > agentgov-status.md || true
            cat agentgov-status.md >> "$GITHUB_STEP_SUMMARY"
            if [ -f agentgov-upgrade-review/UPGRADE_REVIEW.md ]; then
              echo "" >> "$GITHUB_STEP_SUMMARY"
              cat agentgov-upgrade-review/UPGRADE_REVIEW.md >> "$GITHUB_STEP_SUMMARY"
            fi
            if [ -f agentgov-benefit-monitor/BENEFIT_MONITOR.md ]; then
              echo "" >> "$GITHUB_STEP_SUMMARY"
              cat agentgov-benefit-monitor/BENEFIT_MONITOR.md >> "$GITHUB_STEP_SUMMARY"
            fi
          fi
"""
        status_summary = ""
        benefit_summary = ""
        finding_annotations_step = """
      - name: Publish actionable finding annotations
        if: always()
        continue-on-error: true
        run: agentgov benefits annotate agentgov-report.json

      - name: Expose trusted delivery state
        id: delivery_state
        if: always()
        shell: bash
        run: |
          state="missing"
          if [ -f agentgov-benefit-monitor/benefit-monitor.json ]; then
            state="$(jq -r '.state // "missing"' agentgov-benefit-monitor/benefit-monitor.json)"
          fi
          echo "monitor_state=$state" >> "$GITHUB_OUTPUT"
"""
        governance_gate_step = """
      - name: Enforce deterministic governance failures
        if: always()
        shell: bash
        run: |
          test -f agentgov-report.json
          fail_count="$(jq -r '.summary.fail' agentgov-report.json)"
          if [ "$fail_count" -gt 0 ]; then
            echo "AgentGov found $fail_count deterministic failure(s)."
            exit 1
          fi
          echo "AgentGov WARN and ADVISORY findings are visible but non-blocking."
"""
        benefit_artifact = "            agentgov-benefit-monitor\n"
        benefit_baseline_upload = """
      - name: Preserve trusted main benefit baseline
        if: always() && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name != 'pull_request'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: agentgov-main-baseline
          path: |
            agentgov-report.json
            agentgov-benefit-monitor/benefit-monitor.json
          if-no-files-found: warn
          retention-days: 90
"""
        notification_job = """
  surface-governance-regression:
    if: >-
      always() &&
      github.event_name != 'pull_request' &&
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch) &&
      (needs.governance.outputs.monitor_state == 'regression_observed' ||
       needs.governance.outputs.monitor_state == 'mixed_change')
    needs: governance
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Push regression through the workflow conclusion
        shell: bash
        env:
          MONITOR_STATE: ${{ needs.governance.outputs.monitor_state }}
        run: |
          run_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "::error title=AgentGov governance regression::$MONITOR_STATE requires owner review. Evidence: $run_url"
          echo "AgentGov makes this trusted default-branch run red so GitHub can deliver its normal Actions failure notification."
          exit 1

      - name: Preserve notification authority boundary
        if: always()
        run: echo "This read-only signal cannot comment, merge, release, deploy, or modify repository contents."
"""
        proposal_job = f"""
  propose-agentgov-upgrade:
    if: always() && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.create_upgrade_pr))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out default branch for exact-hash revalidation
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{{{ github.event.repository.default_branch }}}}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.11"

      - name: Download verified current AgentGov and latest stable manifest
        shell: bash
        env:
          AGENTGOV_WHEEL_URL: "{resolved_url}"
          AGENTGOV_WHEEL_SHA256: "{wheel_sha256}"
        run: |
          wheel_path="$RUNNER_TEMP/{wheel}"
          curl --fail --location --silent --show-error "$AGENTGOV_WHEEL_URL" --output "$wheel_path"
          echo "$AGENTGOV_WHEEL_SHA256  $wheel_path" | sha256sum --check -
          python -m pip install --no-deps "$wheel_path"
          curl --fail --location --silent --show-error \\
            "https://github.com/Andy-JunXiong/agent-governance-starter/releases/latest/download/release-manifest.json" \\
            --output "$RUNNER_TEMP/agentgov-latest-manifest.json"

      - name: Run current and proposed versions before writing a Draft PR
        shell: bash
        run: |
          agentgov check release-manifest "$RUNNER_TEMP/agentgov-latest-manifest.json"
          agentgov plan upgrade-pr . \\
            --manifest "$RUNNER_TEMP/agentgov-latest-manifest.json" \\
            --format json > "$RUNNER_TEMP/agentgov-upgrade-plan.json"
          current_version="$(jq -r '.current_version' "$RUNNER_TEMP/agentgov-upgrade-plan.json")"
          current_sha="$(grep -m 1 'AGENTGOV_WHEEL_SHA256:' .github/workflows/agentgov.yml | cut -d '"' -f 2)"
          test -n "$current_sha"
          current_filename="agent_governance_starter-$current_version-py3-none-any.whl"
          current_url="https://github.com/Andy-JunXiong/agent-governance-starter/releases/download/v$current_version/$current_filename"
          current_wheel="$RUNNER_TEMP/$current_filename"
          curl --fail --location --silent --show-error "$current_url" --output "$current_wheel"
          echo "$current_sha  $current_wheel" | sha256sum --check -
          python -m venv "$RUNNER_TEMP/agentgov-current"
          "$RUNNER_TEMP/agentgov-current/bin/python" -m pip install --no-deps "$current_wheel"
          set +e
          "$RUNNER_TEMP/agentgov-current/bin/agentgov" report repository . \\
            --format json --output "$RUNNER_TEMP/agentgov-current-report.json"
          current_status="$?"
          set -e
          test -f "$RUNNER_TEMP/agentgov-current-report.json"
          target_version="$(jq -r '.tool_version' "$RUNNER_TEMP/agentgov-latest-manifest.json")"
          target_url="$(jq -r '.artifact.url' "$RUNNER_TEMP/agentgov-latest-manifest.json")"
          target_sha="$(jq -r '.artifact.sha256' "$RUNNER_TEMP/agentgov-latest-manifest.json")"
          target_filename="$(jq -r '.artifact.filename' "$RUNNER_TEMP/agentgov-latest-manifest.json")"
          target_wheel="$RUNNER_TEMP/$target_filename"
          curl --fail --location --silent --show-error "$target_url" --output "$target_wheel"
          echo "$target_sha  $target_wheel" | sha256sum --check -
          python -m venv "$RUNNER_TEMP/agentgov-target"
          "$RUNNER_TEMP/agentgov-target/bin/python" -m pip install --no-deps "$target_wheel"
          set +e
          "$RUNNER_TEMP/agentgov-target/bin/agentgov" report repository . \\
            --format json --output "$RUNNER_TEMP/agentgov-target-report.json"
          target_status="$?"
          set -e
          test -f "$RUNNER_TEMP/agentgov-target-report.json"
          echo "Current AgentGov exit: $current_status; target $target_version exit: $target_status"

      - name: Create or recover bounded AgentGov Draft PR
        shell: bash
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          AGENTGOV_BASE_BRANCH: ${{{{ github.event.repository.default_branch }}}}
        run: |
          started_epoch="$(date +%s)"
          set +e
          agentgov create upgrade-pr . \\
            --manifest "$RUNNER_TEMP/agentgov-latest-manifest.json" \\
            --repository "$GITHUB_REPOSITORY" \\
            --base "$AGENTGOV_BASE_BRANCH" \\
            --event "$GITHUB_EVENT_NAME" \\
            --current-report "$RUNNER_TEMP/agentgov-current-report.json" \\
            --target-report "$RUNNER_TEMP/agentgov-target-report.json" \\
            --format json \\
            > agentgov-upgrade-pr.json
          writer_status="$?"
          set -e
          completed_epoch="$(date +%s)"
          if [ "$writer_status" -eq 0 ] && jq -e . agentgov-upgrade-pr.json > /dev/null; then
            agentgov benefits observe-upgrade agentgov-upgrade-pr.json \\
              --repository "$GITHUB_REPOSITORY" \\
              --commit "$GITHUB_SHA" \\
              --run-id "$GITHUB_RUN_ID" \\
              --started-epoch "$started_epoch" \\
              --completed-epoch "$completed_epoch" \\
              --output agentgov-upgrade-observation
            cat agentgov-upgrade-observation/UPGRADE_OBSERVATION.md >> "$GITHUB_STEP_SUMMARY"
          fi
          exit "$writer_status"

      - name: Upload upgrade proposal result
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: agentgov-upgrade-proposal
          path: |
            agentgov-upgrade-pr.json
            agentgov-upgrade-observation
          if-no-files-found: warn

      - name: Preserve merge and production authority boundary
        if: always()
        run: echo "The Draft PR does not authorize merge, release, deploy, or production execution."
"""
    if _surface == "upgrade":
        if not supports_upgrade_writer:
            raise ValueError("upgrade proposal workflow requires AgentGov 0.3 or newer")
        return f"""# Generated by AgentGov upgrade integration; pinned release {version}.
name: AgentGov Upgrade Proposal

on:
  workflow_dispatch:
    inputs:
      create_upgrade_pr:
        description: "Create or recover an AgentGov upgrade Draft PR"
        required: false
        type: boolean
        default: false
  schedule:
    - cron: "0 13 * * 1-5"

permissions:
  contents: read

jobs:{proposal_job}"""
    if _surface != "governance":
        raise ValueError(f"unsupported consumer workflow surface: {_surface}")
    return f"""# Generated by AgentGov integration; pinned release {version}.
name: AgentGov

on:
  pull_request:
  push:
{workflow_dispatch_trigger}{schedule_trigger}
{workflow_permissions}

jobs:
  governance:
    runs-on: ubuntu-latest
{governance_job_outputs}    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.11"

      - name: Download and verify pinned AgentGov
        shell: bash
        env:
          AGENTGOV_WHEEL_URL: "{resolved_url}"
          AGENTGOV_WHEEL_SHA256: "{wheel_sha256}"
        run: |
{wheel_install_script}{update_manifest_step}{benefit_baseline_step}
      - name: Record update state
        continue-on-error: true
        run: {update_command}
{upgrade_review_step}
      - name: Check repository and write JSON report
{report_continue}        run: agentgov report repository . --format json --output agentgov-report.json{benefit_monitor_step}{finding_annotations_step}{development_monitor_step}

      - name: Add visible governance summary
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          agentgov report repository . --format markdown --output agentgov-report.md || true
{visible_summary}{status_summary}{benefit_summary}
      - name: Upload AgentGov reports
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: agentgov-reports
          path: |
            agentgov-report.json
            agentgov-report.md
{status_artifact}            agentgov-update.json
{benefit_artifact}          if-no-files-found: warn{development_monitor_artifact}{benefit_baseline_upload}{governance_gate_step}

      - name: Preserve human authority boundary
        if: always()
        run: echo "AgentGov findings do not authorize merge, release, deploy, or production execution."
{notification_job}"""


def render_consumer_upgrade_workflow(
    *,
    version: str,
    wheel_url: str | None = None,
    wheel_sha256: str,
) -> str:
    """Render the trusted schedule/dispatch-only upgrade proposal workflow."""

    return render_consumer_workflow(
        version=version,
        wheel_url=wheel_url,
        wheel_sha256=wheel_sha256,
        _surface="upgrade",
    )


def inspect_managed_workflow_content(content: str) -> ManagedConsumerRelease | None:
    """Recognize any byte-exact AgentGov-managed pinned release workflow."""

    header = _MANAGED_HEADER_RE.match(content)
    sha_match = _MANAGED_SHA_RE.search(content)
    if header is None or sha_match is None:
        return None
    version = header.group("version")
    wheel_sha256 = sha_match.group("sha256")
    try:
        expected = render_consumer_workflow(
            version=version,
            wheel_sha256=wheel_sha256,
        )
    except ValueError:
        return None
    if content != expected:
        return None
    return ManagedConsumerRelease(version=version, wheel_sha256=wheel_sha256)


def inspect_managed_upgrade_workflow_content(
    content: str,
) -> ManagedConsumerRelease | None:
    """Recognize a byte-exact schedule/dispatch-only upgrade workflow."""

    header = _MANAGED_UPGRADE_HEADER_RE.match(content)
    sha_match = _MANAGED_SHA_RE.search(content)
    if header is None or sha_match is None:
        return None
    version = header.group("version")
    wheel_sha256 = sha_match.group("sha256")
    try:
        expected = render_consumer_upgrade_workflow(
            version=version,
            wheel_sha256=wheel_sha256,
        )
    except ValueError:
        return None
    if content != expected:
        return None
    return ManagedConsumerRelease(version=version, wheel_sha256=wheel_sha256)


def _resolve_root(root: Path) -> Path:
    if root.is_symlink():
        raise ValueError(f"repository root must not be a symbolic link: {root}")
    if not root.exists():
        raise FileNotFoundError(root)
    if not root.is_dir():
        raise ValueError(f"repository root is not a directory: {root}")
    return root.resolve()


def plan_github_actions_integration(root: Path) -> IntegrationPlan:
    """Plan one create-missing-only workflow without writing."""

    resolved = _resolve_root(root)
    target = resolved / WORKFLOW_PATH
    expected = render_consumer_workflow()
    if target.is_symlink() or target.is_dir():
        item = IntegrationItem(
            IntegrationAction.CONFLICT,
            WORKFLOW_PATH,
            "target must be a regular file and requires human resolution",
        )
    elif target.is_file():
        try:
            current = target.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ValueError(f"cannot read existing workflow: {exc}") from exc
        managed_release = inspect_managed_workflow_content(current)
        if managed_release is not None:
            item = IntegrationItem(
                IntegrationAction.PRESERVE,
                WORKFLOW_PATH,
                f"managed AgentGov {managed_release.version} workflow is already configured",
            )
        else:
            item = IntegrationItem(
                IntegrationAction.CONFLICT,
                WORKFLOW_PATH,
                "existing workflow differs and will not be overwritten",
            )
    else:
        current = resolved
        conflict: Path | None = None
        for part in WORKFLOW_PATH.parts[:-1]:
            current = current / part
            if current.is_symlink() or (current.exists() and not current.is_dir()):
                conflict = current.relative_to(resolved)
                break
        if conflict is not None:
            item = IntegrationItem(
                IntegrationAction.CONFLICT,
                WORKFLOW_PATH,
                f"parent path {conflict.as_posix()} is not a safe directory",
            )
        else:
            item = IntegrationItem(
                IntegrationAction.CREATE,
                WORKFLOW_PATH,
                f"add pinned AgentGov {STABLE_CONSUMER_VERSION} pull-request governance checks",
                expected,
            )
    return IntegrationPlan(resolved, item)


def render_integration_plan_json(
    plan: IntegrationPlan,
    *,
    non_interactive: bool,
) -> str:
    payload = {
        "contract_version": CI_INTEGRATION_CONTRACT_VERSION,
        "tool": {"name": "agentgov", "version": __version__},
        "repository": str(plan.root),
        "mode": "dry_run",
        "interaction": "non_interactive" if non_interactive else "no_prompt",
        "integration": "github-actions",
        "item": {
            "action": plan.item.action.value,
            "path": plan.item.path.as_posix(),
            "reason": plan.item.reason,
            "content": plan.item.content,
        },
        "authority_boundary": {
            "repository_modified": False,
            "write_authorized": False,
            "installs_project_dependencies": False,
            "runs_project_or_production_workflows": False,
            "authorizes_git_or_release_operations": False,
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def request_integration_confirmation(
    plan: IntegrationPlan,
    *,
    decision_reader: Callable[[str], str],
    is_interactive_terminal: bool,
) -> bool:
    if not is_interactive_terminal:
        return False
    decision = decision_reader(
        f'Type INTEGRATE to create "{plan.item.path.as_posix()}" in '
        f'"{plan.root}": '
    )
    return decision == "INTEGRATE"


def apply_integration_plan(plan: IntegrationPlan) -> IntegrationResult:
    """Apply an unchanged CREATE plan using exclusive file creation."""

    if plan.has_conflict:
        raise IntegrationConflictError("integration plan contains a conflict")
    if plan.item.action is IntegrationAction.PRESERVE:
        return IntegrationResult(plan.root, ())
    if plan.item.content is None:
        raise IntegrationConflictError("planned workflow has no deterministic content")

    target = plan.root / plan.item.path
    current = plan.root
    for part in plan.item.path.parts[:-1]:
        current = current / part
        if current.is_symlink():
            raise IntegrationConflictError(
                f"parent path became a symbolic link: "
                f"{current.relative_to(plan.root).as_posix()}"
            )
        if current.exists() and not current.is_dir():
            raise IntegrationConflictError(
                f"parent path became a non-directory: "
                f"{current.relative_to(plan.root).as_posix()}"
            )
    if target.exists() or target.is_symlink():
        raise IntegrationConflictError(
            f"planned target appeared and was not overwritten: {plan.item.path.as_posix()}"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        with target.open("x", encoding="utf-8", newline="") as handle:
            handle.write(plan.item.content)
    except FileExistsError as exc:
        raise IntegrationConflictError(
            f"planned target appeared and was not overwritten: {plan.item.path.as_posix()}"
        ) from exc
    return IntegrationResult(plan.root, (plan.item.path,))


def inspect_consumer_ci(root: Path) -> ConsumerCIStatus:
    """Inspect whether an adopting repository runs AgentGov in GitHub Actions."""

    resolved = _resolve_root(root)
    managed = resolved / WORKFLOW_PATH
    if managed.is_symlink() or managed.is_dir():
        return ConsumerCIStatus(
            ConsumerCIState.CONFLICT,
            (WORKFLOW_PATH,),
            WORKFLOW_PATH,
            "managed workflow path is not a safe regular file",
        )
    if managed.is_file():
        text = managed.read_text(encoding="utf-8")
        managed_release = inspect_managed_workflow_content(text)
        if managed_release is not None:
            return ConsumerCIStatus(
                ConsumerCIState.MANAGED,
                (WORKFLOW_PATH,),
                WORKFLOW_PATH,
                f"managed pinned AgentGov {managed_release.version} workflow is active",
            )

    workflow_root = resolved / ".github/workflows"
    matches: list[Path] = []
    if workflow_root.is_dir() and not workflow_root.is_symlink():
        for path in sorted((*workflow_root.glob("*.yml"), *workflow_root.glob("*.yaml"))):
            if not path.is_file() or path.is_symlink():
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeError):
                continue
            if (
                "agentgov check repository" in text
                or "agentgov report repository" in text
            ):
                matches.append(path.relative_to(resolved))
    if matches:
        return ConsumerCIStatus(
            ConsumerCIState.CUSTOM,
            tuple(matches),
            WORKFLOW_PATH,
            "a custom GitHub Actions workflow invokes AgentGov",
        )
    if managed.is_file():
        return ConsumerCIStatus(
            ConsumerCIState.CONFLICT,
            (WORKFLOW_PATH,),
            WORKFLOW_PATH,
            "agentgov.yml exists but does not invoke the expected repository check",
        )
    return ConsumerCIStatus(
        ConsumerCIState.MISSING,
        (),
        WORKFLOW_PATH,
        "AgentGov is manual-only because no GitHub Actions invocation was found",
    )
